### ISSUE TITLE
SUGGESTION: Add temporary ban setting

### ISSUE THREAD

**Issue by some0ne3** [BlueMond/LifeMC#1]
Hello, 
Can you add temporary ban setting? 
When player is out of lives, he get ban for x(configurable) time. If someone gives his life to a banned player, player gets unban.

I know this plugin is old, but I hope these changes are possible :)

If it's not or you don't have time, can i try my hand editing it?

**Comment by some0ne3** [comment]
@Staartvin can you look? ;)

**Comment by BlueMond** [comment]
I'll look into this soon.
