### ISSUE TITLE
SUGGESTION: Add Hardcore Hearts Look

### ISSUE THREAD

**Issue by Zenomac** [BlueMond/LifeMC#2]
Heyo,

I'd like to thank you for creating such an amazing plugin!
Thank you!

However, it'd be nice to have a feature to be added where there are hardcore hearts.. Now I know there are a few other plugins that do exactly that, but from what I've seen, anytime I use one of those plugins it displays the "Spectate World" instead of the "Respawn" button. I'm not too sure if that's a known issue or if it's just a "feature" but it'd be nice to have that added into your plugin!

Thanks.

**Comment by Staartvin** [comment]
Great to hear you like it! I can look into adding it :)

**Comment by Staartvin** [comment]
Hmm, so I'm wondering. What do you mean exactly with 'hardcore hearts'? How would these work?

**Comment by Zenomac** [comment]
Basically, adding the hardcore hearts look over the normal hearts look. For example:

![image](https://user-images.githubusercontent.com/23299688/87461205-af6aba00-c5d3-11ea-8263-cd0918f77e5b.png)

![image](https://user-images.githubusercontent.com/23299688/87461219-b7c2f500-c5d3-11ea-9622-548af312bf7b.png)

![image](https://user-images.githubusercontent.com/23299688/87461231-bd203f80-c5d3-11ea-8cb7-155a82dbac29.png)

**Comment by Staartvin** [comment]
Hmm, I'm not sure if that's possible without making the player use actual 'hardcore' mode. I don't think those hearts can be shown on demand based on the server. These are client-side changes.

**Comment by BlueMond** [comment]
It may be possible to edit the packets sent between the server and client to force the client to believe that the server is in hardcore mode for the case of deciding what HUD to display. It may of course take a decent bit of work and a knowledge of how Spigot/Bukkit handles packets.

**Comment by Zenomac** [comment]
I have found a plugin that does this but it appears to be no longer updated as the last update for this was on Jun 25, 2017.

https://www.spigotmc.org/resources/heart-changer.42826/
