### ISSUE TITLE
SUGGESTION: grey-list server type ban option

### ISSUE THREAD

**Issue by BlueMond** [BlueMond/LifeMC#3]
"dead" players would still have access to the server, but:

-would only be allowed a certain distance from spawn
-would not be allowed to interact with the world in any other way besides moving within allowed distance from spawn

(Could also maybe allow them outside of spawn radius, but would need a way to visually identify them as a "ghost")

**Comment by Staartvin** [comment]
This is a perfect example of the 'spectator' mode. Players will spawn in spectator mode (and cannot interact with other items).

**Comment by Staartvin** [comment]
You could allow them inside the server, but set their mode to spectator.

**Comment by BlueMond** [comment]
That would be ideal. The only thing that worries me about that, is that players can clip through blocks to possibly scout and assist other players still in the game to cheat. Is there a way to disable the noclip feature of spectator mode?

**Comment by Staartvin** [comment]
What do you think about solutions proposed here: https://www.spigotmc.org/threads/disable-spectator-noclip.136626/

**Comment by BlueMond** [comment]
I was actually just reading that post. I think these may lead towards some viable options to tinker with.
