### ISSUE TITLE
MINOR: Vault check missing from "/lifemc cost" command

### ISSUE THREAD

**Issue by BlueMond** [BlueMond/LifeMC#4]
An error occurs when executing the "/lifemc cost" command due to a missing prior check for the availability of the vault plugin.
EDIT: Only when the vault plugin does not exist.

**Comment by BlueMond** [comment]
The "cost" command may have been overlooked in the most recent code refractor. Currently, there no longer appears to be any preemptive method of querying the cost of a life.

**Comment by Staartvin** [comment]
I removed this command on purpose. Instead, when a player tries to buy a life, he'll get notified how much their balance needs to increase to be able to purchase it.

**Comment by BlueMond** [comment]
But what if the price of a life is steep, they do have enough, and only figure out the cost of it after they make the purchase? 

Edit: Maybe we could integrate it into the buy command if they don't include any arguments?

**Comment by BlueMond** [comment]
Maybe we could integrate it into the buy command if they don't include any arguments?

**Comment by Staartvin** [comment]
Integrating would be nice, yes. Perhaps a good way for you to find out how commands work :P

**Comment by BlueMond** [comment]
Added cost check to buy command without arguments
