### ISSUE TITLE
SUGGESTION: Add placeholders to use outside of plugin

### ISSUE THREAD

**Issue by some0ne3** [BlueMond/LifeMC#8]
1. With player's lives as number
2. With player's lives as symbol/emoji(if possible) (3 lives - ❤❤❤) , when more than 5, use 5x❤ etc

**Comment by BlueMond** [comment]
I'm not sure I understand the nature of the title and request.

**Comment by ghost** [comment]
> 
> 
> I'm not sure I understand the nature of the title and request.

He is probably talking about hooking to and adding live placeholders to PlaceholderAPI (like {lives}), to use these variables from other plugins.

**Comment by BlueMond** [comment]
Ah, I see. Sorry, I wasn't aware of this API, which is why I was confused. I've looked into it, and it looks easy enough to implement. I'll work on adding that next.
